### ISSUE TITLE
 Elección de Lenguaje de Programación

### ISSUE THREAD

**Issue by sorozcov** [eantoniocalo18/IV#18]
Se necesita escoger el lenguaje de programación que se adapte mejor al proyecto.

Avanza en el M1 y el hito de Objetivo2.

**Comment by sorozcov** [comment]
Por favor, añade este issues a #9 y M1. @eantoniocalo18

**Comment by JJ** [comment]
No avanza #9 ni tiene nada que ver con él. Puede avanar un hito, pero ¿de qué forma avanza una historia de usuario, y además específica? Por favor, no os limitéis a "escribir cosas", tratad de poner en práctica los conceptos y lo que son en cada momento.

**Comment by sorozcov** [comment]
Tienes razón, solamente avanza en el hito.
