### ISSUE TITLE
[HU-1-P2] ¿Cómo representar la frecuencia de compra de un producto?

### ISSUE THREAD

**Issue by sorozcov** [eantoniocalo18/IV#19]
Se necesita representar un producto y la periocidad de compra del mismo.

Avanza #9.

**Comment by sorozcov** [comment]
Por favor, añade este issues a #9 y M1. @eantoniocalo18

**Comment by JJ** [comment]
Decir que es un "problema" no es formular el problema. Y decir de antemano que se soluciona con una clase hace que, precisamente, no se solucione el problema sino que directamente se haga la clase. Por favor, tratad de aprender lo que se pide y no solamente seguir la letra del mismo.

**Comment by JJ** [comment]
> Por favor, añade este issues a #9 y M1. @eantoniocalo18

Tienes que añadirlo tú en el cuerpo del issue referenciándolo. Os rogaría que os informárais de cómo hay que hacer las cosas, atendiendo en clase o asistiendo a la misma, en vez de volver a cometer los mismos errores que se han corregido repetidamente en la misma.

**Comment by JJ** [comment]
¿Qué tiene que ver representar un producto con su periodicidad de compra #9? ¿No tendrás que representar la *periodicidad* de la misma?

**Comment by JJ** [comment]
Periodicidad y frecuencia no son lo mismo. Producto y periodicidad son dos cosas diferentes. Parece que finalmente has optado por dos objetos diferentes, lo que es más razonable. Pero hay alternativas: en vez de un objeto por producto, un objeto que tenga las periodicidades de todos los productos. Por eso siempre hay que examinar el problema y cómo se va a usar y sobre todo que el product manager @eantoniocalo18 de retroalimentación a ver qué es lo más correcto.

**Comment by sorozcov** [comment]
> Periodicidad y frecuencia no son lo mismo. Producto y periodicidad son dos cosas diferentes. Parece que finalmente has optado por dos objetos diferentes, lo que es más razonable. Pero hay alternativas: en vez de un objeto por producto, un objeto que tenga las periodicidades de todos los productos. Por eso siempre hay que examinar el problema y cómo se va a usar y sobre todo que el product manager @eantoniocalo18 de retroalimentación a ver qué es lo más correcto.

Creo que #9 se refiere a  la frecuencia del producto y periocidad es un sinónimo del mismo. De igual forma, se cambia el issue a frecuencia que es lo que realmente se desea representar.

**Comment by sorozcov** [comment]
> > Periodicidad y frecuencia no son lo mismo. Producto y periodicidad son dos cosas diferentes. Parece que finalmente has optado por dos objetos diferentes, lo que es más razonable. Pero hay alternativas: en vez de un objeto por producto, un objeto que tenga las periodicidades de todos los productos. Por eso siempre hay que examinar el problema y cómo se va a usar y sobre todo que el product manager @eantoniocalo18 de retroalimentación a ver qué es lo más correcto.
> 
> Creo que #9 se refiere a la frecuencia del producto y periocidad es un sinónimo del mismo. De igual forma, se cambia el issue a frecuencia que es lo que realmente se desea representar.

También se podría luego de tener la clase frecuencia representar un arreglo de todas las frecuencias de cada producto de la clase frecuencia ya creada. Espero la retroalimentación de @eantoniocalo18 para ver que propuesta le parece mejor.

**Comment by eantoniocalo18** [comment]
Un objeto que contenga todas las periodicidades de todos los productos es mucho más eficiente y fácil de programar.
Es la mejor opción. 
Y con respecto a la clase frecuencia que comenta @sorozcov, coincido que también es útil y mejor para el proyecto tener un arreglo con todas las frecuencias, en lugar de un objeto "frecuencia" para cada producto

**Comment by sorozcov** [comment]
He determinado, por lo tanto, cambiar inventario para que puede tener un arreglo de los productos como mencionas así como un diccionario al que se puede acceder que tiene la cantidad de cada producto así como una representación de la frecuencia que en este caso se refiere a la cantidad de producto que se compra en un intervalo de tiempo. Si sientes que la palabra frecuencia no representa a la clase, podemos ver el cambio de este nombre. @eantoniocalo18.
